//2213
// 
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// 

using System.Reflection;

[assembly: AssemblyFileVersion("1.2.1.2213")]
[assembly: AssemblyVersion("1.2.1.2213")]