//2345
// 
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// 

using System.Reflection;

[assembly: AssemblyFileVersion("1.9.1.2345")]
[assembly: AssemblyVersion("1.9.1.2345")]