//2174
// 
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// 

using System.Reflection;

[assembly: AssemblyFileVersion("1.1.0.2174")]
[assembly: AssemblyVersion("1.1.0.2174")]